services:
  postgres:
    image: postgres:16
    container_name: sql_labs_postgres
    environment:
      POSTGRES_DB: sql_labs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres/init/01_init_all.sql:/docker-entrypoint-initdb.d/01_init_all.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sql_labs"]
      interval: 5s
      timeout: 5s
      retries: 20

  mysql:
    image: mysql:8.0
    container_name: sql_labs_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init/01_init_mysql.sql:/docker-entrypoint-initdb.d/01_init_mysql.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: ./data-pipeline
    container_name: sql_labs_app
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: sql_labs
      PG_USER: postgres
      PG_PASSWORD: postgres
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: sql_dm
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy

volumes:
  pg_data:
  mysql_data:

